version: '3'
services:
  mongodb:
    image: mongo
    container_name: user-db
    environment:
      - MONGO_INITDB_DATABASE=user-db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017